import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final polls_numbering_list = [
  FontAwesomeIcons.a,
  FontAwesomeIcons.b,
  FontAwesomeIcons.c,
  FontAwesomeIcons.d,
  FontAwesomeIcons.e,
  FontAwesomeIcons.f,
  FontAwesomeIcons.g,
  FontAwesomeIcons.h,
  FontAwesomeIcons.i,
  FontAwesomeIcons.j,
  FontAwesomeIcons.k,
  FontAwesomeIcons.l,
  FontAwesomeIcons.m,
  FontAwesomeIcons.n,
  FontAwesomeIcons.o,
  FontAwesomeIcons.p,
  FontAwesomeIcons.q,
  FontAwesomeIcons.r,
  FontAwesomeIcons.s,
  FontAwesomeIcons.t,
  FontAwesomeIcons.u,
  FontAwesomeIcons.v,
  FontAwesomeIcons.w,
  FontAwesomeIcons.x,
  FontAwesomeIcons.y,
  FontAwesomeIcons.z,
];
